//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 14/01/2017 13:14:36
namespace ButtonExample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/ButtonPlay.png </summary>
            public const string ButtonPlay_png = "Content/Assets/ButtonPlay.png";
            
            /// <summary> Path to Content/Assets/ButtonPlayOver.png </summary>
            public const string ButtonPlayOver_png = "Content/Assets/ButtonPlayOver.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
